In [1]:
import pandas as pd
import numpy as np

In [2]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[9, 8, 3],
       [6, 1, 6],
       [3, 1, 5]])

In [3]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [4]:
np.arange(0, 21, 7)

array([ 0,  7, 14])

In [5]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]

In [7]:
my_secret

[1, 57, 71, 127, 141, 197, 211, 267, 281]

In [8]:
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [9]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

Потренируемся извлекать из двумерного массива отдельные элементы и их срезы и производить над ними математические действия. Задания блока будем выполнять на примере массива, созданного кодом:

In [10]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
display(big_secret)

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

9.3.1 Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [11]:
summ = 0
for line in big_secret:
    summ += line[-1]
print(summ)

3154.332495807108


9.3.2 Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [12]:
new_d = []
for line in big_secret:
    new_d.append(line[:5])
print(new_d)

[array([14., 10.,  6., 56., 40.]), array([31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573]), array([ 0.,  1.,  4.,  9., 16.]), array([31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573]), array([14., 10.,  6., 56., 40.])]


In [13]:
new_array = np.array(new_d)
new_array.diagonal().sum()

121.37188663699624

9.3.3 Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [14]:
new_m = []
for line in big_secret:
    new_m.append(line[-5:])
print(new_m)

[array([460., 276., 686., 490., 294.]), array([33.04542328, 33.07567082, 33.10589071, 33.13608305, 33.1662479 ]), array([2116., 2209., 2304., 2401., 2500.]), array([33.04542328, 33.07567082, 33.10589071, 33.13608305, 33.1662479 ]), array([460., 276., 686., 490., 294.])]


In [15]:
new_array2 = np.array(new_m)
new_array2.diagonal().prod()

341505315559.2347

Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [16]:
for i in range(big_secret.shape[0]):
    for j in range(big_secret.shape[1]):
        if (i%2 == 1) and (j%2 == 1):
            big_secret[i,j] = 1
        elif (i%2 == 0) and (j%2 == 0):
            big_secret[i,j] = -1
display(big_secret)

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

9.3.4 Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [17]:
new_d2 = []
for line in big_secret:
    new_d2.append(line[:5])
print(new_d2)

[array([-1., 10., -1., 56., -1.]), array([31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573]), array([-1.,  1., -1.,  9., -1.]), array([31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573]), array([-1., 10., -1., 56., -1.])]


In [18]:
new_array3 = np.array(new_d2)
new_array3.diagonal().sum()

-1.0

9.3.5 Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [19]:
new_m2 = []
for line in big_secret:
    new_m2.append(line[-5:])
print(new_m2)

[array([ -1., 276.,  -1., 490.,  -1.]), array([33.04542328,  1.        , 33.10589071,  1.        , 33.1662479 ]), array([-1.000e+00,  2.209e+03, -1.000e+00,  2.401e+03, -1.000e+00]), array([33.04542328,  1.        , 33.10589071,  1.        , 33.1662479 ]), array([ -1., 276.,  -1., 490.,  -1.])]


In [20]:
new_array4 = np.array(new_m2)
new_array4.diagonal().prod()

-1.0

Для выполнения упражнений из следующего блока мы будем использовать массив, созданный с помощью кода:

In [21]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [22]:
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

9.4.1 Сколько столбцов содержит массив great_secret?

In [24]:
great_secret.shape

(100, 3)

9.4.2 Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [27]:
sk = sum(np.cos(great_secret[0]))
sk

0.16006721889793019

9.4.3 Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [29]:
great_secret[great_secret>50].sum()

5470.0

9.4.4 Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [32]:
great_secret.flatten()[150]


7.0710678118654755

9.5.5 Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [39]:
great_sort = np.sort(great_secret, axis=0)
great_sort


array([[ 0.        ,  4.64158883, 40.        ],
       [ 1.        ,  4.65700951, 40.4       ],
       [ 1.41421356,  4.67232873, 40.8       ],
       [ 1.73205081,  4.68754815, 41.2       ],
       [ 2.        ,  4.70266938, 41.6       ],
       [ 2.23606798,  4.71769398, 42.        ],
       [ 2.44948974,  4.73262349, 42.4       ],
       [ 2.64575131,  4.7474594 , 42.8       ],
       [ 2.82842712,  4.76220316, 43.2       ],
       [ 3.        ,  4.77685618, 43.6       ],
       [ 3.16227766,  4.79141986, 44.        ],
       [ 3.31662479,  4.80589553, 44.4       ],
       [ 3.46410162,  4.82028453, 44.8       ],
       [ 3.60555128,  4.83458813, 45.2       ],
       [ 3.74165739,  4.84880759, 45.6       ],
       [ 3.87298335,  4.86294413, 46.        ],
       [ 4.        ,  4.87699896, 46.4       ],
       [ 4.12310563,  4.89097325, 46.8       ],
       [ 4.24264069,  4.90486813, 47.2       ],
       [ 4.35889894,  4.91868473, 47.6       ],
       [ 4.47213595,  4.93242415, 48.   

In [40]:
great_sort[-1].sum()

115.12148016521353

Математические и статистические операции

Модуль NumPy содержит множество базовых статистических функций, которые помогают описать имеющиеся данные: среднее арифметическое (mean), медиана (median), стандартное отклонение (std), корреляция (corrcoef) и прочие. Давайте посмотрим, как они работают. 

Для изучения функций будем использовать набор данных, содержащих информацию об учениках шестого класса. Данные об учениках представлены в таблице:
Создайте массив, содержащий эти данные, и сохраните его под именем students.

In [41]:
students = np.array([[1,135,34,4],[2,160,43,5],[3,163,40,4.3],[4,147,44,5],[5,138,41,4.7],[6,149,54,3.9],
                     [7,136,39,4.2],[8,154,48,4.9],[9,137,35,3.7],[10,165,60,4.6]])

In [42]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

Средние величины

Среднее арифметическое (mean) — сумма всех значений, делённая на их количество, показывает общую тенденцию данных и описывает их одним числом. Узнаем среднюю успеваемость школьников в классе, используя функцию mean:

In [43]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

Медиана — это такое число, что ровно половина элементов из выборки больше него, а другая половина меньше него. Если в выборке есть выбросы (значения, которые принимают величину существенно выше или ниже среднего и выделяются из всей выборки), то медиана будет лучше характеризовать всю выборку, чем среднее арифметическое.

Узнаем, как учится средний ученик, с помощью функции median:

In [44]:
median = np.median(students[:,-1])
median

4.449999999999999

Полученные результаты говорят нам о том, что в среднем школьники учатся хорошо, среди них много отличников (медианное значение среднего балла выше среднего арифметического). Заметим, что школьников в выборке всего 10, а медиана — это значение выборки, при котором ровно половина значений меньше неё, а половина — больше. 

Таким образом, при вычислении медианы Python сначала упорядочит значения по возрастанию, а затем возьмет среднее из серединных элементов полученного ряда. В нашем случае это будут пятый и шестой элементы. Мы можем это проверить, используя функцию sort для сортировки значений оценок: 

In [45]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

9.5.1. Чему равно медианное значение массы тела школьников?

In [46]:
median2 = np.median(students[:,-2])
median2

42.0

9.5.2. На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.

In [47]:
mean2 = np.mean(students[:,-2])
mean2

43.8

In [48]:
mean2-median2

1.7999999999999972

Коэффициент корреляции

Корреляция — статистическая взаимосвязь случайных величин. Мерой корреляции служит одноименный коэффициент, который показывает, насколько сильно связаны величины, он может быть положительным или отрицательным, а по модулю принимает значение от 0 до 1. Отрицательный коэффициент говорит о том, что случайные величины связаны, но при увеличении одной из них вторая уменьшается. Если коэффициент положительный, то величины изменяются в одном направлении.

Аналитики часто оперируют в своей работе данной величиной и ошибаются, делая ложные выводы о данных. Связано это с тем, что не всегда наличие корреляции между двумя показателями говорит о том, что между ними есть причинно-следственная связь.

Давайте узнаем, как связан рост и вес наших школьников, посчитав коэффициент корреляции столбцов матрицы:

In [49]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

Полученный нами коэффициент корреляции составляет чуть больше 0.64. Это говорит о том, что между ростом и весом школьников существует положительная связь: более рослые ученики обычно имеют более высокую массу тела.

9.5.3. Между какой парой признаков в массиве students наблюдается минимальная корреляция?
 - между ростом и массой тела
 - между ростом и успеваемостью
 - между массой тела и успеваемостью 

In [51]:
corr2 = np.corrcoef(students[:,1], students[:,3])
display(corr2)
corr3 = np.corrcoef(students[:,2], students[:,3])
display(corr3)

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

Показатели вариации

Математическое ожидание — среднее значение случайной величины при стремлении числа её измерений к бесконечности. Если число измерений конечно, то для оценки среднего значения величины используется среднее арифметическое. 

Дисперсия — мера разброса случайной величины относительно её математического ожидания. 

 D[X]=M[(X-M[X])**2]

Как следует из формулы, дисперсия случайной величины X равна математическому ожиданию квадрата отклонения случайной величины от ее математического ожидания. То есть, если величина дисперсии небольшая, значит, все числа в выборке имеют близкие друг к другу значения, а чем она больше — тем значительнее разброс показателей.

Стандартное отклонение — самый распространенный показатель рассеивания случайной величины относительно её математического ожидания. 

sigma =sqrt(D[X])

Стандартное отклонение равно квадратному корню из дисперсии. Низкое стандартное отклонение показывает, что все значения в выборке сгруппированы около среднего значения.  Большой показатель этой величины говорит о том, что разброс значений большой. 

Узнаем, насколько разный у школьников рост, посчитав стандартное отклонение std:

In [52]:
std = np.std(students[:,1])
std

11.083320801997928

Полученный результат показывает, что в этом классе одни дети уже начали активно расти, а другие ещё не вступили в период полового созревания. В результате разброс в росте большинства учеников составляет более 11 см от среднего арифметического.

9.5.4. Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов

In [54]:
std2 = np.std(students[:,3])
std2

0.4517742799230607

9.5.5. Посчитайте, чему равна дисперсия значений веса школьников.

Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

numpy.var
numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)

Функция var() вычисляет дисперсию значений элементов массива. 

In [56]:
np.var(students[:,2])

60.36

9.7.4. Перед вами массив my_array. Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

Код должен содержать имя массива и набор индексов для получения нужного среза. В ответе использовать только положительные значения индексов и введите ответ в одну строку без пробелов.

In [57]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [62]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

9.7.5. Создайте массив my_sin, состоящий из синусов элементов массива my_array. Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после запятой.

In [65]:
my_sin = np.sin(my_array)
np.sum(my_sin)

-0.05812430261413351

9.7.6. Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

In [66]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [68]:
my_sin[1:4,1:4] = 1
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [69]:
np.sum(my_sin)

7.571718421269144

9.7.7. Преобразуйте первые четыре столбца массива my_sin в массив из 10 строк и 2 столбцов. Чему равна сумма элементов первого столбца получившегося массива? Ответ округлите до трёх заков после точки-разделителя. Используйте преобразованный в предыдущем задании массив my_sin.

In [70]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [73]:
a = my_sin[:,:4].reshape((10,2))
a

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ],
       [ 1.        ,  1.        ],
       [-0.99999021,  1.        ],
       [ 1.        ,  1.        ],
       [-0.28790332,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836]])

In [76]:
np.sum(a[:,0])

2.4057172058139544

Подготовка массива к заданиям 8-10

Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

In [82]:
bigdata = np.array([x**2 for x in range(100,1001) if x%2==1])
display(bigdata)

array([ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
        13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
        17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
        22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
        27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
        32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
        38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
        45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
        52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
        60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
        68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
        76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
        85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
        95481,  96721,  97969,  99225, 100489, 101761, 103041, 104329,
      

9.7.8. Чему равна медиана массива bigdata?

In [83]:
np.median(bigdata)

302501.0

9.7.9. Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых:

In [84]:
np.std(bigdata)

292095.0301991155

9.7.10. Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами? Введите полученный ответ без изменений и округлений.

In [86]:
bigdata.shape

(450,)

In [88]:
nechet = []
chet = []
for i in range(bigdata.shape[0]):
    if (i%2 == 1):
        nechet.append(bigdata[i])
    elif (i%2 == 0):
        chet.append(bigdata[i])
np.corrcoef(nechet,chet)

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])

Или более компактно

In [89]:
np.corrcoef(bigdata[0::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])